version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - pwd
      - docker-compose up -p 'abc' -d --build
  post_build:
    commands:
      - docker-compose down
